module Kettle
  module Dev
    module Version
      VERSION: String
    end

    class Error < ::StandardError
    end

    DEBUGGING: bool
    IS_CI: bool
    REQUIRE_BENCH: bool
    RUNNING_AS: String
    ENV_TRUE_RE: Regexp
    GEM_ROOT: String

    # Singleton methods
    def self.install_tasks: () -> void
    def self.defaults: () -> Array[String]
    def self.register_default: (String | Symbol task_name) -> Array[String]
  end
end
