module Kettle
  module Dev
    class GemSpecReader
      DEFAULT_MINIMUM_RUBY: Gem::Version

      def self.load: (String root) -> {
        gemspec_path: String?,
        gem_name: String,
        min_ruby: Gem::Version,
        homepage: String,
        gh_org: String,
        forge_org: String,
        funding_org: String?,
        gh_repo: String?,
        namespace: String,
        namespace_shield: String,
        entrypoint_require: String,
        gem_shield: String,
        authors: Array[String],
        email: Array[String],
        summary: String,
        description: String,
        licenses: Array[String],
        required_ruby_version: Gem::Requirement?,
        require_paths: Array[String],
        bindir: String,
        executables: Array[String],
      }

      private
      def self.derive_forge_and_origin_repo: (String? homepage_val) -> { forge_org: String?, origin_repo: String? }
    end
  end
end
