module Kettle
  module Dev
    class GitAdapter
      def initialize: () -> void
      def capture: (Array[String] args) -> [String, bool]
      def push: (String? remote, String branch, force: bool) -> bool
      def current_branch: () -> String?
      def remotes: () -> Array[String]
      def remotes_with_urls: () -> Hash[String, String]
      def remote_url: (String name) -> String?
      def checkout: (String branch) -> bool
      def pull: (String remote, String branch) -> bool
      def fetch: (String remote, String? ref) -> bool
      def clean?: () -> bool
    end
  end
end
