#!/usr/bin/env ruby
# frozen_string_literal: true

# vim: set syntax=ruby

script_basename = File.basename(__FILE__)

begin
  Kernel.exec(Gem.ruby, Gem.bin_path("kettle-gha-pins", "kettle-gha-pins"), *ARGV)
rescue Gem::Exception, LoadError => e
  warn("#{script_basename}: could not load kettle-gha-pins executable: #{e.class}: #{e.message}")
  warn("Hint: Install the kettle-gha-pins gem (`gem install kettle-gha-pins`) or add it to your Gemfile.")
  exit(1)
end
