#!/usr/bin/env ruby
# frozen_string_literal: true

# vim: set syntax=ruby

# Immediate, unbuffered output
$stdout.sync = true
# Ensure bundler is set up by the host project
require "bundler/setup"

require "kettle/dev"

puts "== kettle-readme-backers v#{Kettle::Dev::Version::VERSION} =="

Kettle::Dev::ReadmeBackers.new.run!
